version: "3.8"
services:
  alpine-ftp:
    image: kllmkll/alpine-ftp-server
    environment:
      USERS: "one|1234 two|1234"
      ADDRESS: 192.168.111.202
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - ./ftp:/ftp
